# Generated by Django 3.1.5 on 2024-04-18 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('programme_curriculum', '0002_auto_20240418_0345'),
        ('academic_procedures', '0001_initial'),
    ]

    operations = [
        
    ]
